server:
  port: 8081

gateway:
  api-backend: http://localhost:8080
  users:
    - { username: zhangsan, password: "123456", user-id: zhangsan }
    - { username: lisi,     password: "123456", user-id: lisi }